### PR TITLE
Added colab notebook and included tensorboardX as requirement

### PR DESCRIPTION
**Pull request by t04glovern**
- Added notebook example for colab
- Included tenbsorboardX dependency that was required (even outside of colab)
- Fixed small bug in demo.py referring to the wrong configuration file

### CODE REVIEW

**Comment by t04glovern** [comment]
I can double check tomorrow, but I had a strange dependency error relating to it (even locally in conda). Happy to exclude it from the PR though

**Comment by nkolot** [comment]
I'm fine with adding it, I was just wondering. Maybe some other package was trying to import it. Do you remember where did you get the import error? In the collab notebook?

**Comment by nkolot** [comment]
Sorry it's my bad. I left a tensorboardX import after the cleanup in utils/base_trainer.py.
This should be replaced with from torch.utils.tensorboard import SummaryWriter.

**Comment by nkolot** [comment]
So if you could make this change as well and test that it works I will merge it asap.

**Comment by t04glovern** [comment]
Should be all sorted now, I've tested it on my end, seems okay

**Comment by nkolot** [comment]
Ok, I'm merging it.

**Pull request merged**
